# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
      with:
        elixir-version: '>=1.15' # Define the elixir version [required]
        otp-version: '>=26' # Define the OTP version [required]
    - name: Restore dependencies cache - Saga
      uses: actions/cache@v3
      with:
        path: saga/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies - Saga
      run: mix deps.get
      working-directory: saga
    - name: Run tests - Saga
      run: mix test
      working-directory: saga
    - name: Restore dependencies cache - Web
      uses: actions/cache@v3
      with:
        path: saga_web/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies - Web
      run: mix deps.get
      working-directory: saga_web
    - name: Run tests - Wb]eb
      run: mix test
      working-directory: saga_web
